site_name: Jihan Web
# site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep-purple
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xJihan
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/0xJih4n
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/0xJihan/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/0xJihan" target="_blank" rel="noopener">Jihan</a>
